- id: '1638798449986'
  alias: Test bouton
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 27211aae0efdc7c6c2eefc3231c0c7aa
    entity_id: binary_sensor.switch_158d0001d62031
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 7bc445788dba2770f8ea198f312f3e4b
    entity_id: light.yeelight_meuble1
    domain: light
  mode: single
- id: '1638801103543'
  alias: Test_button
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 27211aae0efdc7c6c2eefc3231c0c7aa
    entity_id: binary_sensor.switch_158d0001d62031
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 7bc445788dba2770f8ea198f312f3e4b
    entity_id: light.yeelight_meuble1
    domain: light
  mode: single
