# dchaumond configuration
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  # Packages
  packages: 
    domoticz: !include domoticz.yaml
    harmony: !include harmony.yaml
    roborock: !include roborock.yaml
    thermostat: !include thermostat.yaml
    alexa: !include alexa.yaml
    emulated_hue: !include emulated_hue.yaml
    ###broadlink: !include broadlink.yaml
    # Weather underground is no more available for free ...
    #weather: !include weather.yaml
    special: !include special.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
  
# Enables the frontend
frontend:

# Enables configuration UI
config:

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue
    - yeelight
   
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

logger:
  #default: critical
  default: error
  #default: info
  #default: debug
  #logs:
    #homeassistant.components.alexa.smart_home: debug

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Mobile
mobile_app:

# 
sensor:
  - platform: template
    sensors:
      salon:
        value_template: '{{ states.remote.salon.attributes.current_activity }}'
        friendly_name: 'Harmony'

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
        
#Xiaomi
xiaomi_aqara:
   discovery_retry: 10
   gateways:
     - key: !secret xiaomi_aqara_key
       mac: !secret xiaomi_aqara_mac
       host: !secret xiaomi_aqara_host

#MQTT
#mqtt:
#  broker: !secret mqtt_broker_host
#  port: !secret mqtt_broker_port
#  discovery: true
#  discovery_prefix: homeassistant
        
switch: !include_dir_merge_list switchs/

light: !include_dir_merge_list lights/
yeelight: !include yeelight.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
