sensor:
  - platform: mqtt
    state_topic: 'home/sensor/260/temp'
    name: 'dz Sonde Chambre Haut'
    unit_of_measurement: '째C'

  - platform: mqtt
    state_topic: 'home/sensor/257/temp'
    name: 'dz Sonde Terrasse'
    unit_of_measurement: '째C'
 
  - platform: mqtt
    state_topic: 'home/sensor/248/temp'
    name: 'dz Sonde Salon'
    unit_of_measurement: '째C'

  - platform: mqtt
    state_topic: 'home/sensor/255/temp'
    name: 'dz Sonde Chambre sport'
    unit_of_measurement: '째C'
    
switch:
  - platform: mqtt
    name: "Prise meuble salon"
    command_topic: "home/switch/126/power"
    state_topic: "home/switch/126/state"
    payload_on: "On"
    payload_off: "Off"
    qos: 1
    retain: true

  - platform: command_line
    switches:
      tv_switch:
        command_on: 'curl "http://192.168.1.150:8080/json.htm?type=command&param=switchlight&idx=126&switchcmd=On"'
        command_off: 'curl "http://192.168.1.150:8080/json.htm?type=command&param=switchlight&idx=126&switchcmd=Off"'
        friendly_name: Prise TV
      buanderie_switch:
        command_on: 'curl "http://192.168.1.150:8080/json.htm?type=command&param=switchlight&idx=262&switchcmd=On"'
        command_off: 'curl "http://192.168.1.150:8080/json.htm?type=command&param=switchlight&idx=262&switchcmd=Off"'
        friendly_name: Buanderie
