sensor:
  - platform: yr
  - platform: wunderground
    api_key: !secret wunderground_api_key
    pws_id: !secret wunderground_pws_id
    lang: FR
    monitored_conditions:
      - location
      - alerts
      - weather
      - temp_c
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - weather_3d_metric
      - weather_3n_metric
      - weather_4d_metric
      - weather_4n_metric
