- platform: yeelight
  devices:
    192.168.1.221:
      name: yeelight_canape
    192.168.1.222:
      name: yeelight_meuble1
    192.168.1.223:
      name: yeelight_meuble2
    192.168.1.224:
      name: yeelight_meuble3
    192.168.1.228:
      name: yeelight_terrasse_salon
    192.168.1.229:
      name: yeelight_terrasse_bbcue
