# Ask for sonoffs states at start
- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "/sonoffs/cmnd/state"
        payload: "" 
        
- alias: Turn on light when motion is detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e542b5
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dcb2472f
        brightness: 170
        color_name: blue
    #- service: switch.turn_on
    #  entity_id: switch.nuc_flash_green

- alias: Turn off light motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e542b5
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dcb2472f
    #- service: switch.turn_off
    #  entity_id: switch.nuc_flash_green

# Test ...
- alias: Turn green long click
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        event_id: binary_sensor.switch_158d0001d62031
        click_type: long_click_press
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dcb2472f
        brightness: 170
        color_name: green

# Turn on/off meuble
- alias: Turn on/off meuble
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        event_id: binary_sensor.switch_158d0001d62031
        click_type: single
  action:
    - service: homeassistant.toggle
      entity_id: group.meuble
        
# Toggle gw double click
- alias: Turn off
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        event_id: binary_sensor.switch_158d0001d62031
        click_type: double
  action:
    - service: homeassistant.toggle
      entity_id: light.gateway_light_7811dcb2472f
        
- alias: Turn on buanderie
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000222e329
      to: 'on'
  action:
    - condition: state
      entity_id: 'switch.buanderie_switch'
      state: 'off'
    - service: switch.turn_on
      data:
        entity_id: switch.buanderie_switch

- alias: Turn off buanderie
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000222e329
      to: 'off'
  action:
    - condition: state
      entity_id: 'switch.buanderie_switch'
      state: 'on'
    - service: switch.turn_off
      data:
        entity_id: switch.buanderie_switch

