#
# MQTT - DZ
#        
- alias: DZ thermostat get value
  initial_state: true
  #hide_entity: false
  trigger:
     - platform: mqtt
       topic: 'domoticz/out'
  condition: 
     condition: template
     value_template: '{{ trigger.payload_json.dtype == "Thermostat" }}'
  action:
     - service: mqtt.publish
       data_template:
         topic: 'home/thermostat/{{ trigger.payload_json.idx }}/state'
         payload_template: '{{ trigger.payload_json.svalue1 }}'
               
- alias: DZ switch send value as dz expect
  initial_state: true
  #hide_entity: false
  trigger:
     - platform: mqtt
       topic: 'home/switch/+/power'
  action:
     - service: mqtt.publish
       data_template:
         topic: 'domoticz/in'
         payload_template: '{"command": "switchlight", "idx": {{ trigger.topic.split("/")[-2] }}, "switchcmd": "{{ trigger.payload }}" }'
             
- alias: DZ thermostat send value as dz expect
  initial_state: true
  #hide_entity: false
  trigger:
     - platform: mqtt
       topic: 'home/thermostat/+/target'
  action:
     - service: mqtt.publish
       data_template:
         topic: 'domoticz/in'
         payload_template: '{"command": "udevice", "idx": {{ trigger.topic.split("/")[-2] }}, "svalue": "{{ trigger.payload }}"}'
